export const UPDATE_ISLAND = "UPDATE_ISLAND";
export const UPDATE_CONFIG = "UPDATE_CONFIG";
export const UPDATE_STATS = "UPDATE_STATS";
export const UPDATE_CONFIG_RANGE_INTERVAL = "UPDATE_CONFIG_RANGE_INTERVAL";
export const UPDATE_CONFIG_TYPE_REQUEST = "UPDATE_CONFIG_TYPE_REQUEST";
export const UPDATE_CONFIG_CELL_SIZE = "UPDATE_CONFIG_CELL_SIZE";
export const UPDATE_CONFIG_COUNT_ROW = "UPDATE_CONFIG_COUNT_ROW";
export const UPDATE_CONFIG_COUNT_COLUMN = "UPDATE_CONFIG_COUNT_COLUMN";